---
title: "Assignment 7"
author: "Adriana LH"
date: "10/31/2020"
output: html_document
---

```{r}
library(tidycensus)
library(tidyverse)
library(sf)
library(leaflet)
library(htmltools)
library(htmlwidgets)
library(raster)
library(gstat)
library(spatial)
```


```{r}
evictions_boston <- read_csv("boston_20201024.csv") %>%
  mutate(GEOID10 = as.numeric (str_sub(GEOID,-11,-1))) 

boston_tracts <- st_read("https://bostonopendata-boston.opendata.arcgis.com/datasets/4a8eb4fb3be44ed5a1eec28551b9f3b2_0.geojson?outSR=%7B%22latestWkid%22%3A3857%2C%22wkid%22%3A102100%7D") %>%
   mutate (GEOID10 = as.numeric(GEOID10))
```



```{r}
test <- evictions_boston %>%
  group_by(GEOID10, racial_majority) %>%
summarise(total = sum(filings_2020))
```

vars <- c(total_pop ="B01003_001")

population <-  get_acs(geography = "tract",
                     variables = vars,
                     state = "MA",
                     county = "Suffolk",
                     output = "wide") %>%

```{r}
evictions <- left_join(boston_tracts, test, by = "GEOID10") %>%

na.omit(evictions)

evictions$label <- 
  paste(evictions$racial_majority, "racial majority <br>", 
        evictions$total, "total evictions in each tract") %>% 
  lapply(htmltools::HTML)

bins <- seq(min(evictions$total),
            max(evictions$total), by = 5)
pal <- colorNumeric("viridis", 
                    domain = evictions$total,
                    na.color = "#00000000")

leaflet(evictions) %>%
  addProviderTiles(providers$Stamen.TonerLite) %>%
  addPolygons(highlightOptions = highlightOptions(fillOpacity = 1),
              label = ~label,
              fillColor = ~pal(total),
              weight = 1, color = "black") %>% 
   addControl('<a href="https://evictionlab.org/eviction-tracking/get-the-data/">Data source</a>',
             position = "bottomleft") %>%
  addLegend(pal = pal, 
            values = ~total,
            bins = 10,
            opacity = 0.7, title = "Total Evictions In Each Tract",
            position = "topright")

```

```{r}
MA_state_plane <- "+proj=lcc +lat_1=41.71666666666667 +lat_2=42.68333333333333 +lat_0=41 +lon_0=-71.5 +x_0=200000 +y_0=750000 +ellps=GRS80 +units=m +no_defs "

WGS84 <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"

tract_points <- st_centroid(
  st_transform(evictions, crs = MA_state_plane)) %>%
  st_transform(WGS84)

leaflet(tract_points) %>%
  addProviderTiles(providers$Stamen.TonerLite) %>%
  addCircles(label = ~label,
             fillColor = ~pal(total),
             stroke = FALSE, 
             radius = 50, 
             fillOpacity = 1) %>% 
  addControl('<a href="https://evictionlab.org/eviction-tracking/get-the-data/">Data source</a>',
             position = "bottomleft") %>%
  addLegend(pal = pal, 
            values = ~total,
            bins = 10,
            opacity = 0.7, title = "Total Evictions in Each Tract",
            position = "topright")
```

```{r}
tract_points_sp <- tract_points %>%
  st_transform(MA_state_plane) %>%
  as_Spatial()

tract_poly_sp <- evictions %>%
  st_transform(MA_state_plane) %>%
  as_Spatial()

eviction_raster <- raster(tract_poly_sp, res=10)

gs <- gstat(formula=total~1, locations=tract_points_sp)
idw_interp <- interpolate(eviction_raster, gs)

idw_interp_clip <- mask(idw_interp, tract_poly_sp)

leaflet(tract_points) %>%
  addProviderTiles(providers$Stamen.TonerLite) %>%
  addRasterImage(idw_interp_clip, colors = pal, opacity = 0.8) %>% 
   addControl('<a href="https://evictionlab.org/eviction-tracking/get-the-data/">Data source</a>',
             position = "bottomleft") %>%
  addLegend(pal = pal, 
            values = ~total,
            bins = 10,
            opacity = 0.7, title = "Total Evictions in Each Tract",
            position = "topright")
```

