---
title: "Vis Assignment 6"
author: "Adriana LH"
date: "10/25/2020"
output: 
 html_document:
    theme: cosmo
    highlight: zenburn
---
```{r load libraries, include = FALSE}
library(tidyverse)
library(sf)
library(leaflet)
library(htmltools)
library(htmlwidgets)
library(ggthemes)
library(ggspatial)
library(viridis)
```

```{r}
leaflet_plane <- "+proj=longlat +datum=WGS84"

neighborhoods <- st_read("http://bostonopendata-boston.opendata.arcgis.com/datasets/3525b0ee6e6b427f9aab5d0a1d0a1a28_0.geojson?outSR=%7B%22latestWkid%22%3A2249%2C%22wkid%22%3A102686%7D") %>%
st_transform(crs =leaflet_plane)
```
```{r}
neighborhoods$describe <- 
  paste(neighborhoods$Name, "<br>") %>%
  lapply(htmltools::HTML)

neighborhoods_map <-leaflet(neighborhoods) %>%
  addProviderTiles(providers$Stamen.TonerLite) %>%
  addPolygons(fillColor = "bisque", stroke = FALSE,
              highlightOptions = highlightOptions(fillColor = "darksalmon", 
                                                  fillOpacity = 1),
              label = ~describe) %>%
  addPolylines(data = neighborhoods, stroke = T, 
               color = "burlywood", 
               opacity = 1,
               weight = 1) %>%
  addControl("Park Locations in Seattle", position = "topright") %>%
  addControl('<a href="http://bostonopendata-boston.opendata.arcgis.com/datasets/3525b0ee6e6b427f9aab5d0a1d0a1a28_0.geojson?outSR=%7B%22latestWkid%22%3A2249%2C%22wkid%22%3A102686%7D">Data source</a>',
             position = "bottomleft")
neighborhoods_map
```

```{r}
saveWidget(neighborhoods_map, file = "neighborhoods.html")
```

